---
name: Translate README → Spanish (no API key)

"on":
  push:
    paths:
      - README.md
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install translator (Argos Translate)
        run: |
          python -m pip install --upgrade pip
          pip install "argostranslate==1.9.6"

      - name: Translate README to Spanish (offline)
        run: |
          python - <<'PY'
          import pathlib, sys, textwrap, re
          from argostranslate import package, translate

          SRC = pathlib.Path("README.md")
          OUT = pathlib.Path("README.es.md")

          if not SRC.exists():
            print("README.md not found", file=sys.stderr)
            sys.exit(1)

          # Make sure EN->ES package is installed
          available = package.get_available_packages()
          pkg = next((p for p in available
                      if p.from_code == "en" and p.to_code == "es"), None)
          if pkg:
            package.install_from_path(pkg.download())

          # Fallback if the model is already present (no-op) or installed above
          translate.load_installed_packages()
          translator = translate.get_translation("en", "es")

          text = SRC.read_text(encoding="utf-8")

          # Preserve fenced code blocks: translate only non-code parts
          # Handles ```lang ... ``` and ~~~ fences.
          parts = []
          code = False
          fence = None
          for line in text.splitlines(keepends=True):
            m = re.match(r"^(\s*)(```|~~~)", line)
            if m:
              token = m.group(2)
              if not code:
                code = True
                fence = token
                parts.append(("text", ""))  # ensure segment boundary
                parts.append(("code", line))
              else:
                # closing fence (treat any fence as close to be robust)
                code = False
                fence = None
                parts.append(("code", line))
                parts.append(("text", ""))  # boundary
              continue
            parts.append(("code" if code else "text", line))

          # Merge contiguous segments
          merged = []
          for kind, line in parts:
            if merged and merged[-1][0] == kind:
              merged[-1] = (kind, merged[-1][1] + line)
            else:
              merged.append((kind, line))

          out_chunks = []
          for kind, chunk in merged:
            if kind == "code":
              out_chunks.append(chunk)  # keep code unchanged
            else:
              if chunk.strip():
                out_chunks.append(translator.translate(chunk))
              else:
                out_chunks.append(chunk)

          banner = textwrap.dedent("""\
          <!--
          ⚠️ Generado automáticamente.
          Este archivo (README.es.md) se produce a partir de README.md
          por un flujo de trabajo de GitHub Actions.
          Los cambios directos aquí podrían sobrescribirse.
          -->
          """)

          OUT.write_text(banner + "".join(out_chunks), encoding="utf-8")
          print(f"✅ Wrote {OUT}")
          PY

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update README.es.md (offline translation)"
          branch: ci/translate-readme
          title: "Auto-translate README → Spanish (no API key)"
          body: |
            This PR updates **README.es.md** from **README.md** using
            Argos Translate (open-source, no API key).
            - Source: README.md
            - Target: README.es.md
            - Translator: Argos (OPUS-MT)
          add-paths: |
            README.es.md
